import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/NavbarNext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} sticky top-0 w-full`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
